version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    groups:
      production-updates:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-updates:
        dependency-type: "development"
        update-types:
          - "major"
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "npm-backend"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    groups:
      production-updates:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-updates:
        dependency-type: "development"
        update-types:
          - "major"
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "npm-frontend"
